# Generated by Django 2.0.1 on 2018-01-23 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('viplevels', '0001_initial'),
        ('users', '0002_auto_20180123_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteMessge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('hasread', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='userAuthinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.ImageField(upload_to=users.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='vipLevelChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
                ('destlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destlevel', to='viplevels.vipLevel')),
                ('orignallevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orignallevel', to='viplevels.vipLevel')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='viplevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viplevels.vipLevel'),
        ),
        migrations.AddField(
            model_name='viplevelchangehistory',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userauthinfo',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitemessge',
            name='fromuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitemessge',
            name='touser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destlevel', to=settings.AUTH_USER_MODEL),
        ),
    ]
