# Generated by Django 2.0.1 on 2018-01-23 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180123_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemessge',
            name='touser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL),
        ),
    ]
