# Generated by Django 2.0.1 on 2018-03-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthinfo',
            old_name='imgurl',
            new_name='img',
        ),
    ]
