# Generated by Django 2.0.1 on 2018-04-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180329_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currentpoint',
            field=models.CharField(choices=[('ck', '等待管理员审核'), ('bc', '被退回')], max_length=100, null=True),
        ),
    ]
