# Generated by Django 2.0.1 on 2018-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_currentpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemessge',
            name='publishdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemessge',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
