# Generated by Django 2.0.1 on 2018-06-06 14:35

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180417_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatearea',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitemessge',
            name='status',
            field=models.CharField(choices=[('pass', '审核通过'), ('waitting', '等待审核'), ('reject', '审核驳回')], default='waitting', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='wechat_qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.wechat_qr_path),
        ),
        migrations.AddField(
            model_name='viplevelchangehistory',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='viplevelchangehistory',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sitemessge',
            name='touser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='userid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viplevelchangehistory',
            name='orignallevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orignallevel', to='viplevels.vipLevel'),
        ),
    ]
